<?xml version="1.0" encoding="utf-8"?><Database Name="NhaSach" Class="MyDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-CIHCNRO8\SQLEXPRESS;Initial Catalog=NhaSach;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="NhaSachConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTietDonHang" Member="ChiTietDonHangs">
    <Type Name="ChiTietDonHang">
      <Column Name="madon" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="masach" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soluong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="DonHang_ChiTietDonHang" Member="DonHang" ThisKey="madon" OtherKey="madon" Type="DonHang" IsForeignKey="true" />
      <Association Name="Sach_ChiTietDonHang" Member="Sach" ThisKey="masach" OtherKey="masach" Type="Sach" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonHang" Member="DonHangs">
    <Type Name="DonHang">
      <Column Name="madon" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="thanhtoan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="giaohang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ngaydat" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ngaygiao" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="makh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DonHang_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="madon" OtherKey="madon" Type="ChiTietDonHang" />
      <Association Name="KhachHang_DonHang" Member="KhachHang" ThisKey="makh" OtherKey="makh" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="makh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tendangnhap" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="matkhau" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="dienthoai" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="ngaysinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="KhachHang_DonHang" Member="DonHangs" ThisKey="makh" OtherKey="makh" Type="DonHang" />
    </Type>
  </Table>
  <Table Name="dbo.Sach" Member="Saches">
    <Type Name="Sach">
      <Column Name="masach" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="maloai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tensach" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="hinh" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="giaban" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ngaycapnhat" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="soluongton" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Sach_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="masach" OtherKey="masach" Type="ChiTietDonHang" />
      <Association Name="TheLoai_Sach" Member="TheLoai" ThisKey="maloai" OtherKey="maloai" Type="TheLoai" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TheLoai" Member="TheLoais">
    <Type Name="TheLoai">
      <Column Name="maloai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tenloai" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="TheLoai_Sach" Member="Saches" ThisKey="maloai" OtherKey="maloai" Type="Sach" />
    </Type>
  </Table>
</Database>